{
 "title": "OPNSense",
 "description": "Dashboard for the OPNsense Prometheus Exporter\n\nhttps://github.com/rknightion/opnsense-exporter",
 "tags": [
  "opnsense",
  "firewall",
  "networking",
  "prometheus-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "opnsense_instance",
    "label": "OPNSense Instance",
    "query": {
     "query": "label_values(opnsense_up,opnsense_instance)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,2m,5m,10m,20m,30m" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OPNSense Exporter Scrapes Total",
   "type": "stat",
   "description": "Total number of scrapes by the OPNsense exporter",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opnsense_exporter_scrapes_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{opnsense_instance}}"
    }
   ]
  },
  {
   "title": "OPNSense Status",
   "type": "timeseries",
   "description": "The current status of OPNsense (1 = up, 0 = down)",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_up{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{opnsense_instance}} Status"
    }
   ]
  },
  {
   "title": "OPNSense Scrape Endpoint Errors",
   "type": "timeseries",
   "description": "The total errors by endpoint returned by the OPNsense API during data fetching\t",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_exporter_endpoint_errors_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Services Status History",
   "type": "status-history",
   "description": "Status points of services uptime\n\n1 - Available \n0 - Unavailable",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_services_status{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Gateway RTT",
   "type": "timeseries",
   "description": "RTT is the average (mean) of the round trip time in milliseconds by name",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "opnsense_gateways_rtt_milliseconds{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gateway RTTd",
   "type": "timeseries",
   "description": "RTTd is the standard deviation of the round trip time in milliseconds by name",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "opnsense_gateways_rttd_milliseconds{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gateway Loss Percentage",
   "type": "timeseries",
   "description": "Gateway Loss Percentage by Gateway Name",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "opnsense_gateways_loss_percentage{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Gateway Status History",
   "type": "status-history",
   "description": "Status points of the gateway uptime. \n\n1 - Available \n0 - Unavailable",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_gateways_status{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "[RATE $rate_interval]] Received Bytes By Interface",
   "type": "timeseries",
   "description": "Total received data with applied range function by the Rate Interval selector",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_received_bytes_total{opnsense_instance=\"$opnsense_instance\"}[$rate_interval])",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "[RATE $rate_interval] Transmitted Bytes By Interface",
   "type": "timeseries",
   "description": "Total transmitted data with applied range function by the Rate Interval selector",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_transmitted_bytes_total{opnsense_instance=\"$opnsense_instance\"}[$rate_interval])",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Interfaces [ Device - Name ] MTU",
   "type": "stat",
   "description": "MTU of the interface by interface name and device",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opnsense_interfaces_mtu_bytes{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "[TOTAL] Received Bytes By Interface",
   "type": "timeseries",
   "description": "Total received data by interface ",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opnsense_interfaces_received_bytes_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "[TOTAL] Transmitted Bytes By Interface",
   "type": "timeseries",
   "description": "Total transmitted data by interface",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "opnsense_interfaces_transmitted_bytes_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{device}} - {{interface}}"
    }
   ]
  },
  {
   "title": "[TOTAL] Errors By Interface",
   "type": "timeseries",
   "description": "Total transmitted data by interface",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_interfaces_input_errors_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "INPUT Errors {{device}} - {{interface}}"
    },
    {
     "expr": "opnsense_interfaces_input_errors_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "OUTPUT Errors  {{device}} - {{interface}}"
    }
   ]
  },
  { "title": "ARP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "ARP Table Entries ",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "opnsense_arp_table_entries{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "{{interface_description}} - {{hostname}} - {{mac}}"
    }
   ]
  },
  {
   "title": "[RATE $rate_interval] ARP Requests",
   "type": "timeseries",
   "description": "Rate of Sent and Received ARP requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(opnsense_protocol_arp_sent_requests_total{opnsense_instance=\"$opnsense_instance\"}[$rate_interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(opnsense_protocol_arp_received_requests_total{opnsense_instance=\"$opnsense_instance\"}[$rate_interval])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "[TOTAL] ARP Requests",
   "type": "timeseries",
   "description": "Total of Sent and Received ARP requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_protocol_arp_sent_requests_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "Sent"
    },
    {
     "expr": "opnsense_protocol_arp_received_requests_total{opnsense_instance=\"$opnsense_instance\"}",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}