package syslog

// OPN-0104: grammars observed in the retained Camden corpus. Fields remain log
// attributes, never metric labels; peer-supplied detail is never an event name.
func init() {
	capturedEvent("/usr/sbin/cron", "cron_parse_failed", `\(([^\s()]+)\) PARSE \((bad minute)\)`, "cron.user", "cron.error")
	capturedEvent("cron", "cron_parse_failed", `\(([^\s()]+)\) PARSE \((bad minute)\)`, "cron.user", "cron.error")
	capturedEvent("configd.py", "config_command_timeout", `Timeout \((\d+)\) executing : ([^\r\n]+)`, "config.timeout_seconds", "config.command")
	capturedEvent("configd.py", "config_disconnected", `Configd disconnected while executing : ([^\r\n]+)`, "config.command")
	capturedEvent("configd.py", "config_unavailable", `failed waiting for configd \(doesn't seem to be running\)`)
	capturedEvent("configd.py", "config_socket_failed", `Failed to connect to configd socket: ([^\r\n]*) while executing ([^\r\n]+)`, "error.message", "config.command")
	capturedEvent("configctl", "config_socket_failed", `unable to connect to configd socket \((@/var/run/[^\s()]+)\)`, "config.socket")
	capturedEvent("php", "backup_connection_failed", `error connecting to (Google Drive)`, "backup.provider")
	for _, program := range []string{"pkg", "pkg-static"} {
		capturedEvent(program, "package_upgraded", `(\S+) upgraded: (\S+) -> (\S+)`, "package.name", "package.version.previous", "package.version")
	}
	capturedEvent("audit", "firmware_update_executed", `\[Firmware\] User (\S+) executed a firmware update`, "audit.user")
	capturedEvent("shutdown", "reboot_requested", `reboot by ([^\s:]+):`, "audit.user")
	capturedEvent("dnsmasq", "dns_query", `query\[([A-Z0-9]+)\] (\S+) from (\S+)`, "dns.query_type", "dns.query_name", "src.ip")
	capturedEvent("dnsmasq", "dns_config_answer", `config (\S+) is (\S+)`, "dns.query_name", "dns.answer")
	capturedEvent("dnsmasq", "dns_upstream_missing", `warning: no upstream servers configured`)
	capturedEvent("dnsmasq-dhcp", "dhcp_send_failed", `Error sending DHCP packet to (\S+): ([^\r\n]+)`, "dst.ip", "error.message")
	capturedEvent("dhclient", "dhcp_packet_length_mismatch", `ip length (\d+) disagrees with bytes received (\d+)\.`, "network.ip_length", "network.received_bytes")
	capturedEvent("dhclient", "dhcp_packet_trailing_data", `accepting packet with data after udp payload\.`)
	capturedEvent("dhcp6c", "dhcp6_address_remove_failed", `failed to remove an address on ([\w.-]+): ([^\r\n]+)`, "interface", "error.message")
	capturedEvent("dhcp6c", "dhcp6_prefix_removed", `remove a site prefix ([0-9A-Fa-f:]+/\d+)`, "dhcp6c.prefix")
	capturedEvent("dhcp6c", "dhcp6_restarting", `restarting`)
	capturedEvent("dhcp6c", "dhcp6_release_started", `Start address release`)
	capturedEvent("dhcp6c", "dhcp6_reload_requested", `rtsold_script: reloading dhcp6c`)
	capturedEvent("lldpd", "lldp_send_failed", `unable to send packet on real device for ([\w.-]+): ([^\r\n]+)`, "interface", "error.message")
	capturedEvent("lldpd", "lldp_control_socket_missing", `no control socket path registered`)
	capturedEvent("firewall", "geoip_update_failed", `geoip update failed : ([^\r\n]+) \[http_code: (\d{3})\]`, "error.message", "http.response.status_code")
	capturedEvent("miniupnpd", "upnp_interface_address_failed", `failed to get address for interface ([\w.-]+)`, "interface")
	capturedEvent("radvd", "router_advertisement_send_failed", `sendmsg: ([^\r\n]+)`, "error.message")
	capturedEvent("sshd-session", "ssh_transport_failed", `Read error from remote host (\S+) port (\d+): ([^\r\n]+)`, "src.ip", "src.port", "error.message")
	capturedEvent("sshd-session", "ssh_key_exchange_failed", `error: kex_exchange_identification: read: ([^\r\n]+) \[preauth\]`, "error.message")
	capturedEvent("syslog-ng", "syslog_connection_failed", `Syslog connection failed; fd='(\d+)', server='AF_INET\(([^\s']+):(\d+)\)', error='([^'\r\n]+)', time_reopen='(\d+)'`, "syslogng.fd", "dst.ip", "dst.port", "error.message", "syslogng.time_reopen_seconds")
	capturedEvent("dpinger", "gateway_send_failed", `(\S+) (\S+): sendto error: (\d+)`, "gateway.name", "gateway.address", "error.code")
	capturedEvent("kernel", "interface_link_changed", `(?:<\d+>)?(?:\[\d+\] )?([\w.-]+): link state changed to (UP|DOWN)`, "interface", "interface.link_state")
	capturedEvent("devd", "interface_notification", `Processing event '!system=IFNET subsystem=([\w.-]+) type=(LINK_UP|LINK_DOWN|ADDR_ADD|ADDR_DEL)(?: (?:inet|inet6)=(\S+))?'`, "interface", "interface.notification", "interface.address")
	capturedEvent("ntpd", "clock_unsynchronized", `kernel reports TIME_ERROR: (0x[0-9a-fA-F]+): Clock Unsynchronized`, "ntp.status")
	capturedEvent("ntpd", "clock_kernel_sync_changed", `(\S+) [0-9a-fA-F]+ [0-9a-fA-F]+ kern kernel time sync (enabled|disabled)`, "ntp.peer", "ntp.kernel_sync")
	capturedEvent("ntpd", "clock_peer_event", `(\S+) [0-9a-fA-F]+ [0-9a-fA-F]+ (sys_peer|no_sys_peer|clock_sync|reachable|restart)`, "ntp.peer", "ntp.event")
	capturedEvent("ntpd", "clock_peer_demobilized", `(\S+) [0-9a-fA-F]+ [0-9a-fA-F]+ demobilize assoc (\d+)`, "ntp.peer", "ntp.association")
	capturedEvent("ntpd", "clock_peer_mobilized", `(\S+) [0-9a-fA-F]+ [0-9a-fA-F]+ mobilize assoc (\d+)`, "ntp.peer", "ntp.association")
	capturedEvent("ntpd", "clock_offset_spike", `(\S+) [0-9a-fA-F]+ [0-9a-fA-F]+ popcorn ([+-]?\d+\.\d+) s`, "ntp.peer", "ntp.offset_seconds")
	capturedEvent("ntpd", "clock_frequency_set", `(\S+) [0-9a-fA-F]+ [0-9a-fA-F]+ freq_set kernel ([+-]?\d+\.\d+) PPM`, "ntp.peer", "ntp.frequency_ppm")
	capturedEvent("ppp", "ppp_protocol_event", `\[([\w.-]+)\] (LCP|IPCP|IPV6CP): (Up|Down|Open|Close) event`, "ppp.link", "ppp.protocol", "ppp.transition")
	capturedEvent("ppp", "ppp_protocol_layer", `\[([\w.-]+)\] (LCP|IPCP|IPV6CP): (LayerUp|LayerDown|LayerStart|LayerFinish)`, "ppp.link", "ppp.protocol", "ppp.transition")
	capturedEvent("ppp", "ppp_bundle_joined", `\[([\w.-]+)\] Link: Join bundle "([\w.-]+)"`, "ppp.link", "ppp.bundle")
	capturedEvent("ppp", "ppp_bundle_left", `\[([\w.-]+)\] Link: Leave bundle "([\w.-]+)"`, "ppp.link", "ppp.bundle")
	capturedEvent("ppp", "ppp_bundle_closing", `\[([\w.-]+)\] Bundle: No NCPs left\. Closing links\.\.\.`, "ppp.bundle")
	capturedEvent("ppp", "ppp_interface_renamed", `\[([\w.-]+)\] IFACE: Rename interface ([\w.-]+) to ([\w.-]+)`, "ppp.bundle", "interface.previous", "interface")
	capturedEvent("ppp", "ppp_chap_result", `\[([\w.-]+)\] CHAP: rec'd (SUCCESS|FAILURE) #(\d+) len: (\d+)`, "ppp.link", "ppp.chap_result", "ppp.packet_id", "ppp.packet_length")
	capturedEvent("dnsmasq", "dns_hosts_answer", `(/[\w/.-]+) (\S+) is (\S+)`, "dns.hosts_file", "dns.query_name", "dns.answer")

}
