package main

import (
	"fmt"
	"strconv"
	"strings"
)

// composeRequiredPlaceholders gives an obvious placeholder value for every
// kingpin-Required flag, so the reference compose file's environment: mapping
// has real strings sitting where OPNsense connection details go rather than
// an empty quote. A Required flag with no entry here fails the build (see
// generateComposeReference) instead of rendering an empty placeholder: silently
// missing one is exactly the coverage gap this page exists to close.
var composeRequiredPlaceholders = map[string]string{
	"opnsense.protocol": "https",
	"opnsense.address":  "opnsense.example.com",
}

// composeReceiverPorts documents the three push receivers' listen ports in the
// generated ports: block. Each entry names the flag that turns the receiver on,
// since an operator scanning ports: has no other way to connect "why is this
// commented out" to "what enables it".
type composePort struct {
	published, containerPort, proto string
	enabledBy                       string
	note                            string
}

var composeReceiverPorts = []composePort{
	{
		published: "5514", containerPort: "5514", proto: "udp",
		enabledBy: "logs.syslog.enabled",
		note: "Syslog UDP. Publish BOTH the UDP and TCP lines below - the commonest " +
			"reason a syslog target appears to send nothing is that only one transport " +
			"got published.",
	},
	{
		published: "5514", containerPort: "5514", proto: "tcp",
		enabledBy: "logs.syslog.enabled",
		note:      "Syslog TCP. See the UDP line above.",
	},
	{
		published: "9200", containerPort: "9200", proto: "",
		enabledBy: "logs.zenarmor.enabled",
		note: "Zenarmor's Elasticsearch-shaped stream. 9200 is only the Elasticsearch " +
			"convention; nothing requires it, it just has to match the URI configured " +
			"in Zenarmor.",
	},
	{
		published: "2055", containerPort: "2055", proto: "udp",
		enabledBy: "flow.netflow.enabled",
		note: "NetFlow v5/v9. UNAUTHENTICATED - restrict with flow.netflow.allowed-peers " +
			"or a firewall rule before publishing this on a shared network.",
	},
}

const composeCommentWidth = 88

// generateComposeReference renders the exhaustive Compose reference page: one
// compose file in which every exporter setting appears, commented out at its
// default, grouped by groupFlags. It complements docs/deployment/docker.md,
// which stays a short quick-start; this page is the coverage artifact.
func generateComposeReference(out *output, path string, flags []FlagDoc) {
	if unmatched := groupFlagsUnmatched(flags); len(unmatched) > 0 {
		fatal("compose reference: flags matched by no group rule (add a prefix to "+
			"groupRules in flaggroups.go): %v", unmatched)
	}
	for _, f := range flags {
		if f.Required {
			if _, ok := composeRequiredPlaceholders[f.Name]; !ok {
				fatal("compose reference: required flag %q has no placeholder in "+
					"composeRequiredPlaceholders", f.Name)
			}
		}
	}
	out.write(path, renderComposeReference(flags))
}

// renderComposeReference is the pure renderer: no filesystem, no check-mode
// branching, deterministic for a given flag list. Kept separate from
// generateComposeReference so tests exercise it directly.
func renderComposeReference(flags []FlagDoc) []byte {
	groups := groupFlags(flags)

	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: Docker Compose Reference\n")
	b.WriteString("description: Every opnsense2otel setting, commented out at its default, in one Docker Compose file\n")
	b.WriteString("tags:\n")
	b.WriteString("  - Deployment\n")
	b.WriteString("  - Docker\n")
	b.WriteString("  - Reference\n")
	b.WriteString("---\n\n")
	b.WriteString("# Docker Compose Reference\n\n")
	b.WriteString("**Generated by `make docs`. Do not hand-edit — edits here are overwritten on the next run.**\n\n")
	b.WriteString("Every flag the exporter knows about, grouped the same way as [Configuration](../configuration.md), " +
		"rendered as a single Compose file with each setting commented out at its default. " +
		"For a short working example, see [Docker & Compose](docker.md); this page exists so a new " +
		"setting cannot ship without a place in an example config.\n\n")
	b.WriteString("Flags with no environment variable (`--config.check` is the only one today) cannot live in " +
		"`environment:` at all — they are documented as comments and belong in `command:` instead.\n\n")

	b.WriteString("```yaml title=\"docker-compose.yml\"\n")
	b.WriteString("services:\n")
	b.WriteString("  opnsense2otel:\n")
	b.WriteString("    image: ghcr.io/rknightion/opnsense2otel:latest\n")
	b.WriteString("    container_name: opnsense2otel\n")
	b.WriteString("    restart: always\n")
	b.WriteString("\n")

	writeFlagOnlySection(&b, flags)

	b.WriteString("    environment:\n")
	for _, g := range groups {
		writeGroupBanner(&b, g)
		for _, f := range g.Flags {
			writeComposeFlagEntry(&b, f)
		}
		b.WriteString("\n")
	}

	writePortsSection(&b)

	b.WriteString("```\n")
	return []byte(b.String())
}

// writeFlagOnlySection documents every flag with no env var. It runs before
// environment: (flag-only settings are command:-only) and is generated from
// the flag list rather than a hardcoded name, so a second flag-only flag shows
// up here automatically instead of needing this function edited by hand.
func writeFlagOnlySection(b *strings.Builder, flags []FlagDoc) {
	var flagOnly []FlagDoc
	for _, f := range flags {
		if f.Envar == "" {
			flagOnly = append(flagOnly, f)
		}
	}
	if len(flagOnly) == 0 {
		return
	}
	b.WriteString("    # Flag-only settings: no environment variable exists, so these can only be\n")
	b.WriteString("    # passed as command-line arguments. Uncomment into command: to use one, not\n")
	b.WriteString("    # into environment: below.\n")
	b.WriteString("    # command:\n")
	for _, f := range flagOnly {
		for _, line := range wrapComposeComment("    #   ", f.Help) {
			b.WriteString(line)
			b.WriteString("\n")
		}
		fmt.Fprintf(b, "    #   - --%s\n", f.Name)
	}
	b.WriteString("\n")
}

func writeGroupBanner(b *strings.Builder, g FlagGroup) {
	b.WriteString("      # ==========================================================================\n")
	fmt.Fprintf(b, "      # %s\n", g.Title)
	for _, line := range wrapComposeComment("      # ", g.Blurb) {
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString("      # ==========================================================================\n")
}

// writeComposeFlagEntry renders one flag as a help comment plus its env var
// line. Flag-only flags (no env var) were already fully documented in
// writeFlagOnlySection, so here they get a one-line pointer instead of a
// second full write-up.
func writeComposeFlagEntry(b *strings.Builder, f FlagDoc) {
	if f.Envar == "" {
		fmt.Fprintf(b, "      # --%s has no env var - see the flag-only settings note above command:.\n", f.Name)
		return
	}
	for _, line := range wrapComposeComment("      # ", f.Help) {
		b.WriteString(line)
		b.WriteString("\n")
	}
	value := yamlQuote(f.Default)
	if placeholder, ok := composeRequiredPlaceholders[f.Name]; ok {
		fmt.Fprintf(b, "      %s: %s\n", f.Envar, yamlQuote(placeholder))
		return
	}
	fmt.Fprintf(b, "      # %s: %s\n", f.Envar, value)
}

func writePortsSection(b *strings.Builder) {
	b.WriteString("    ports:\n")
	fmt.Fprintf(b, "      - \"%s:8080\" # web.listen-address - the /metrics and operator-console port.\n", "8080")
	b.WriteString("\n")
	b.WriteString("      # The receivers below listen on their own ports and are all off by default.\n")
	b.WriteString("      # Publish a port only once its receiver is enabled.\n")
	for _, p := range composeReceiverPorts {
		for _, line := range wrapComposeComment("      # ", fmt.Sprintf("%s (--%s)", p.note, p.enabledBy)) {
			b.WriteString(line)
			b.WriteString("\n")
		}
		spec := fmt.Sprintf("%s:%s", p.published, p.containerPort)
		if p.proto != "" {
			spec = fmt.Sprintf("%s/%s", spec, p.proto)
		}
		fmt.Fprintf(b, "      # - \"%s\"\n", spec)
	}
}

// yamlQuote renders s as a double-quoted YAML scalar, escaping the characters
// that would otherwise end the quote or start an escape early. Every rendered
// value goes through this: env var defaults are untrusted free text (flag help
// and defaults are Go string literals today, but nothing enforces that stays
// true), and an unescaped default containing a quote would corrupt the
// document silently rather than failing loudly.
func yamlQuote(s string) string {
	return strconv.Quote(s)
}

// wrapComposeComment wraps text into '<prefix>word word ...' lines no wider
// than composeCommentWidth, so long flag help strings do not produce a single
// unreadable line in the generated file. prefix already ends in a space where
// one is wanted; it is repeated verbatim on every line.
//
// Named distinctly from env_example.go's wrapComment (different signature:
// prefix-string vs width-only, since Compose lines are indented under
// services.opnsense2otel.environment and .env's are not).
func wrapComposeComment(prefix, text string) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return []string{strings.TrimRight(prefix, " ")}
	}
	var lines []string
	cur := prefix
	empty := true
	for _, w := range words {
		candidate := cur
		if !empty {
			candidate += " "
		}
		candidate += w
		if !empty && len(candidate) > composeCommentWidth {
			lines = append(lines, cur)
			cur = prefix + w
			empty = false
			continue
		}
		cur = candidate
		empty = false
	}
	lines = append(lines, cur)
	return lines
}
