package main

import (
	"fmt"
	"strings"
)

// envExampleWrapWidth is the target comment width. 88, not 80: several help
// strings quote a flag name or an env var inline and wrap ugly just past 80.
const envExampleWrapWidth = 88

// envVarName derives OPNSENSE_EXPORTER_FOO from a flag's own Envar when set,
// or from its dotted --flag.name otherwise. All 200 flags in the kingpin
// model already carry one or the other; the fallback exists only so a future
// flag added without an explicit Envar still renders instead of vanishing.
func envVarName(f FlagDoc) string {
	if f.Envar != "" {
		return f.Envar
	}
	return "OPNSENSE_EXPORTER_" + strings.ToUpper(strings.NewReplacer(".", "_", "-", "_").Replace(f.Name))
}

// wrapComment word-wraps text into "# "-prefixed lines at width. Greedy
// wrap, not textwrap-optimal: this is a config file comment, not typeset
// prose, and greedy keeps the output stable as help text is edited.
func wrapComment(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}
	var lines []string
	line := "# " + words[0]
	for _, w := range words[1:] {
		if len(line)+1+len(w) > width {
			lines = append(lines, line)
			line = "# " + w
			continue
		}
		line += " " + w
	}
	lines = append(lines, line)
	return lines
}

// generateEnvExample renders the complete environment-variable reference to
// .env.example. Every flag appears exactly once, commented out (this is a
// reference file, not a config an operator can accidentally half-fill and
// have silently override defaults), except the two flags kingpin marks
// Required — those are what a copied file must actually have filled in, so
// they render uncommented with a placeholder.
func generateEnvExample(out *output, path string, flags []FlagDoc) {
	out.write(path, []byte(renderEnvExample(flags)))
}

// renderEnvExample builds the .env.example content. Split from
// generateEnvExample so tests can assert on the string directly instead of
// reading a file back off disk (wiring the write into main.go's call
// sequence is a separate change; this package only owns the renderer).
func renderEnvExample(flags []FlagDoc) string {
	if unmatched := groupFlagsUnmatched(flags); len(unmatched) > 0 {
		fatal("env_example: flags matched by no group rule (add a prefix to groupRules in flaggroups.go): %v", unmatched)
	}

	var b strings.Builder
	b.WriteString("# .env.example -- full environment-variable reference for the OPNsense exporter.\n")
	b.WriteString("#\n")
	b.WriteString("# GENERATED by `make docs` (scripts/docgen/env_example.go). Do not hand-edit.\n")
	b.WriteString("#\n")
	b.WriteString("# Every line below is commented out and set to the flag's default, so copying this\n")
	b.WriteString("# file verbatim into .env changes nothing. Uncomment and edit only the variables you\n")
	b.WriteString("# want to override. The two REQUIRED variables are the exception: they have no default,\n")
	b.WriteString("# so they are left uncommented with a placeholder that must be replaced.\n")

	for _, group := range groupFlags(flags) {
		b.WriteString("\n")
		b.WriteString(strings.Repeat("#", envExampleWrapWidth))
		b.WriteString("\n")
		fmt.Fprintf(&b, "# %s\n", group.Title)
		for _, line := range wrapComment(group.Blurb, envExampleWrapWidth) {
			b.WriteString(line)
			b.WriteString("\n")
		}
		b.WriteString(strings.Repeat("#", envExampleWrapWidth))
		b.WriteString("\n")

		for _, f := range group.Flags {
			b.WriteString("\n")
			writeFlagEntry(&b, f)
		}
	}

	return b.String()
}

func writeFlagEntry(b *strings.Builder, f FlagDoc) {
	for _, line := range wrapComment(f.Help, envExampleWrapWidth) {
		b.WriteString(line)
		b.WriteString("\n")
	}
	fmt.Fprintf(b, "# flag: --%s\n", f.Name)

	env := f.Envar
	if env == "" {
		// --config.check is the one flag with no env var equivalent: it only
		// makes sense as a one-shot CLI invocation, never a standing setting.
		fmt.Fprintf(b, "# flag-only, no environment variable equivalent\n")
		return
	}

	switch {
	case f.Required:
		fmt.Fprintf(b, "# REQUIRED -- no default, the exporter refuses to start without this\n")
		fmt.Fprintf(b, "%s=\n", env)
	case f.Default == "":
		fmt.Fprintf(b, "# unset by default\n")
		fmt.Fprintf(b, "#%s=\n", env)
	default:
		fmt.Fprintf(b, "#%s=%s\n", env, f.Default)
	}
}
