"""Frozen dashboard UID registry and context-preserving URL builder (#419).

Navigation is the one dashboard element that can be *confidently wrong*. An empty
panel reads "No data" and an operator distrusts it; a link that lands on the right
dashboard with a different instance selected, or a different time window, looks like
it worked — and the responder then compares two firewalls and believes the answer.
So every link is built here, from a registry, rather than written at a call site.

## The registry

A UID is permanent in a way a title is not: it is in every bookmark, every alert
notification, every runbook. `DESTINATIONS` is therefore the single source of truth,
and it carries an `exists` flag as well as a UID.

`exists=False` is the whole reason this file has a flag rather than a list. The
self-observability dashboard `opnsense-exporter-health` is RESERVED — the owner froze
the UID on 2026-07-27 so #431 can be built against it, ahead of the dashboard
existing. Emitting a link to it now would produce exactly the broken navigation #419
exists to prevent, so `dash_url()` refuses a reserved destination and the build fails
rather than shipping a 404. When #431 lands, one flag flips.

`RETIRED_UIDS` is the never-reuse list. All three 404 today; they were companion
dashboards that were deleted, and a link to one of them would be indistinguishable
from a typo.

## Why the URL is spelled out rather than left to `keepTime` / `includeVars`

Grafana's `DashboardLink` has `keepTime` and `includeVars` booleans that do this
implicitly. They are not used, for two reasons: `includeVars` propagates EVERY
variable including the ~96 hidden presence sentinels (`skipUrlSync` mitigates that
but is a property of the variable, not of the link, so a new sentinel that forgets it
leaks silently), and a panel-level `DataLink` has no such booleans at all — its only
input is the URL. One explicit URL shape, used by both, is testable in a way two
mechanisms are not.

Three interpolations do the work:

* `${__url_time_range}` — expands to `from=…&to=…`, preserving absolute windows.
* `${opnsense_instance:queryparam}` — expands to `var-opnsense_instance=…`, repeated
  per selected value, so a multi-select or `All` survives the jump. The variable NAME
  is part of the expansion; that is why these tokens are not written as `var-x=…`.
* `${datasource:queryparam}` — the reader's own datasource, never a UID from our
  stack. `${loki_datasource:queryparam}` is added only for a log-facing destination.

## Tab targeting

The dashboard is a TabsLayout of domains, each holding a nested TabsLayout of leaf
tabs, and Grafana syncs the selected tab to the URL: `dtab=<domain slug>` for the
top-level layout, and `<domain slug>-dtab=<leaf slug>` for the nested one (the key is
`dtab` rather than `tab` because panel edit already owns `tab`). A slug is the tab
title with runs of spaces collapsed to single hyphens — case and punctuation are
preserved, which is why the value must be percent-encoded: `Firewall & PF` would
otherwise truncate the query string at the ampersand.

Derived from Grafana's own `TabsLayoutManager`/`getSlugForRowOrTab` on `main`
(2026-07-27). The deployed stack reports 13.2.0, which has no matching OSS tag to pin
against, so this is verified against source rather than against the running build —
and it degrades safely: a Grafana that does not honour `dtab` opens the dashboard on
its default tab with the time range and instance still correct. Nothing 404s.
`tests/test_links.py` checks every emitted slug against the tab titles this build
actually produced, so a renamed tab fails the build instead of quietly mis-targeting.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from urllib.parse import quote


@dataclass(frozen=True)
class Destination:
    """One dashboard this project may link to.

    `exists` is a statement about the WORLD, not about intent: True means the
    dashboard is generated by this repository today and a link to it resolves.
    """

    uid: str
    title: str
    exists: bool
    why: str


MAIN_UID = "opnsense-exporter"
HEALTH_UID = "opnsense-exporter-health"

DESTINATIONS: dict[str, Destination] = {
    MAIN_UID: Destination(
        uid=MAIN_UID,
        title="OPNsense Exporter",
        exists=True,
        why="the operational dashboard generated by grafana/build_dashboard.py; "
            "every in-dashboard drilldown targets it",
    ),
    HEALTH_UID: Destination(
        uid=HEALTH_UID,
        title="OPNsense Exporter Health",
        exists=True,
        why="self-observability dashboard (Diagnostics + Log Shipping), generated by "
            "grafana/build_dashboard.py into dashboard-health.json. The UID was frozen "
            "by owner decision 2026-07-27 and reserved with exists=False until #431 "
            "generated it; flipped True in that same commit, which is what allowed the "
            "main dashboard's link to it to be emitted at all.",
    ),
}

# Never reuse. Each returned 404 on the live stack when checked on 2026-07-25.
RETIRED_UIDS: dict[str, str] = {
    "rovp4pp": "original hand-built OPNsense dashboard, deleted when the generated "
               "one replaced it",
    "opnsense-network-activity": "OPNsense — Network Activity companion, deleted; its "
                                 "content lives in the Interfaces and Flow tabs",
    "ddfj9vprnpio74a": "OPNsense SFP & Port Monitor companion, deleted; migrated onto "
                       "exporter metrics in the main dashboard",
    "opnsense-zenarmor": "OPNsense Zenarmor companion, retired by #435 after its nine "
                         "unique DNS/web/application panels were merged into the "
                         "generated Zenarmor tab. There is deliberately nothing to link "
                         "to: the owner's 2026-07-27 decision made Zenarmor a "
                         "sentinel-gated tab of the main dashboard, and an in-dashboard "
                         "tab needs no link",
}

# Project URLs a link may point at. Not stack-specific: these are the project's own
# documentation and repository, which every importer of the dashboard can reach.
DOCS_BASE = "https://m7kni.io/opnsense-exporter/"
REPO_BASE = "https://github.com/rknightion/opnsense-exporter"
# #430: repointed from the README's old flat inventory table to the generated
# per-rule runbook document. This constant is the INDEX link (the dashboard's single
# "Alert runbooks" DashboardLink, and any other place that wants "the runbooks doc"
# rather than one specific rule) - the anchor names the document's own top-level
# heading, which `grafana/tests/test_manifest_contract.py` checks resolves for real.
# Individual alerts get their own anchor from `runbook_url()` below instead.
RUNBOOK_URL = f"{REPO_BASE}/blob/main/grafana/runbooks.md#alerts--recording-rules"
EXTERNAL_LINK_BASES = (DOCS_BASE, REPO_BASE)

# Schema v2's placement for a control that belongs in the dropdown rather than on the
# always-visible toolbar (#470). v2-only, which is fine: Grafana 13 is the only
# supported target.
CONTROLS_MENU = "inControlsMenu"

URL_TIME_RANGE = "${__url_time_range}"
INSTANCE_PARAM = "${opnsense_instance:queryparam}"
DS_PARAM = "${datasource:queryparam}"
LOKI_DS_PARAM = "${loki_datasource:queryparam}"

_SPACES = re.compile(r" +")


def tab_slug(title: str) -> str:
    """Grafana's tab slug: runs of spaces collapsed to one hyphen, nothing else."""
    return _SPACES.sub("-", title.strip())


# ---- GitHub Markdown heading-anchor algorithm ------------------------------
# Shared home for the slugger (#430): both `runbook_url()` below (which must EMIT an
# anchor that GitHub will actually produce) and `grafana/alerts/validate_manifests.py`
# (which must independently RESOLVE that anchor against runbooks.md) need the exact
# same algorithm. Keeping one copy here, imported by both, is what makes "the anchor
# resolves" a real check rather than two slugs happening to agree by coincidence.
_HEADING_SLUG_STRIP_RE = re.compile(r"[^\w\s-]")
_HEADING_SLUG_WS_RE = re.compile(r"\s")


def github_heading_slug(text: str) -> str:
    """Approximate GitHub's Markdown heading-anchor algorithm: lowercase, drop
    punctuation (keep word chars/spaces/hyphens), then turn each whitespace
    character into its own hyphen - GitHub does not collapse the doubled
    hyphen a removed '&' leaves behind, e.g. "Alerts & Recording" ->
    "alerts--recording"."""
    text = text.strip().lower()
    text = _HEADING_SLUG_STRIP_RE.sub("", text)
    return _HEADING_SLUG_WS_RE.sub("-", text)


def runbook_url(title: str) -> str:
    """Per-rule anchor into the generated runbook document (#430). `title` is the
    rule's own `title` field (e.g. "OPNsenseExporterDown"), rendered as that exact
    "## <title>" heading in `grafana/runbooks.md` by
    `grafana/alerts/build_rules.py`'s `generate_runbooks_md()` - so the anchor this
    produces is guaranteed to name a real heading, not a document built separately
    from the same list, by construction."""
    return f"{REPO_BASE}/blob/main/grafana/runbooks.md#{github_heading_slug(title)}"


def _encode_slug(slug: str) -> str:
    # Percent-encode everything Grafana's own slug allows through that a query
    # string does not: `&` (Firewall & PF) would otherwise end the parameter.
    return quote(slug, safe="-_.~")


def dash_url(*, uid: str = MAIN_UID, tab: tuple[str, str] | None = None,
             variables: dict[str, str] | None = None, loki: bool = False) -> str:
    """Build a relative dashboard URL that carries the current context.

    uid        destination; must be registered AND exist (see module docstring).
    tab        (domain tab title, leaf tab title) to open on arrival, or None to
               land on the destination's default tab.
    variables  extra `var-<name>=<value>` pairs. Values may use Grafana
               interpolations, e.g. `${__field.labels.interface}` in a field link.
    loki       also propagate the Loki datasource, for a log-facing destination.
    """
    if uid in RETIRED_UIDS:
        raise ValueError(
            f"{uid!r} is a RETIRED dashboard UID ({RETIRED_UIDS[uid]}); it 404s and "
            "must never be linked or reused")
    dest = DESTINATIONS.get(uid)
    if dest is None:
        raise ValueError(
            f"{uid!r} is not a registered destination; add it to uids.DESTINATIONS "
            "with an exists flag and a reason rather than typing a UID at a call site")
    if not dest.exists:
        raise ValueError(
            f"{uid!r} is RESERVED and not generated yet ({dest.why}); linking to it "
            "would emit navigation that 404s")

    params = [URL_TIME_RANGE, INSTANCE_PARAM, DS_PARAM]
    if loki:
        params.append(LOKI_DS_PARAM)
    if tab is not None:
        domain, leaf = tab
        domain_slug = tab_slug(domain)
        params.append(f"dtab={_encode_slug(domain_slug)}")
        if leaf:
            params.append(f"{_encode_slug(domain_slug)}-dtab={_encode_slug(tab_slug(leaf))}")
    for name, value in (variables or {}).items():
        params.append(f"var-{name}={value}")
    return f"/d/{uid}?" + "&".join(params)


def data_link(title: str, *, uid: str = MAIN_UID, tab: tuple[str, str] | None = None,
              variables: dict[str, str] | None = None, loki: bool = False,
              new_tab: bool = False) -> dict:
    """A `DataLink` (v2 `PanelSpec.links` / `fieldConfig.defaults.links` entry)."""
    link: dict[str, object] = {
        "title": title,
        "url": dash_url(uid=uid, tab=tab, variables=variables, loki=loki)}
    if new_tab:
        link["targetBlank"] = True
    return link


def external_link(title: str, url: str, *, tooltip: str = "") -> dict:
    """A dashboard-level `DashboardLink` to a project URL (docs, runbooks).

    `keepTime`/`includeVars` are false: the destination is not a Grafana dashboard,
    so dashboard context would be meaningless query noise on it.
    """
    if not url.startswith(EXTERNAL_LINK_BASES):
        raise ValueError(
            f"{url!r} is not one of this project's own URLs; a generated dashboard "
            "must not embed a third-party or stack-specific address")
    return {"title": title, "type": "link", "url": url, "icon": "external link",
            "tooltip": tooltip, "tags": [], "asDropdown": False, "targetBlank": True,
            "includeVars": False, "keepTime": False,
            # Dashboard links share the controls area with 16 annotation toggles, which
            # rendered as three rows of chrome above the tab bar (#470). Documentation
            # and runbooks are read once, not toggled while reading a graph, so they
            # belong in the v2 controls menu.
            "placement": CONTROLS_MENU}


def dashboard_link(title: str, *, uid: str = MAIN_UID,
                   tab: tuple[str, str] | None = None, tooltip: str = "") -> dict:
    """A dashboard-level `DashboardLink` to another dashboard of ours.

    The URL is built explicitly rather than via `includeVars`, which would also
    propagate every hidden presence sentinel.
    """
    return {"title": title, "type": "link",
            "url": dash_url(uid=uid, tab=tab), "icon": "dashboard",
            "tooltip": tooltip, "tags": [], "asDropdown": False, "targetBlank": False,
            "includeVars": False, "keepTime": False, "placement": CONTROLS_MENU}


# ---- ready-made drilldowns ------------------------------------------------
# Written once here rather than per call site so that "focus this interface" means
# the same thing on every panel that offers it.

def focus_interface(label: str = "interface") -> dict:
    """Field link: re-scope the whole dashboard to the clicked description-space
    interface (`$interface`: LAN, IOT — #98's label space)."""
    return data_link(
        "Focus this interface across the dashboard",
        variables={"interface": f"${{__field.labels.{label}}}"})


def focus_device(label: str = "interface") -> dict:
    """Field link: re-scope the dashboard to the clicked kernel device name
    (`$device`: igb0, pppoe0). The label carrying it differs by metric family —
    pf and vnStat publish it as `interface`, the info metrics as `device` (#424)."""
    return data_link(
        "Focus this device across the dashboard",
        variables={"device": f"${{__field.labels.{label}}}"})


def to_tab(title: str, domain: str, leaf: str, *, loki: bool = False,
           uid: str = MAIN_UID,
           variables: dict[str, str] | None = None) -> dict:
    """Panel link: another tab, same instance and time window.

    `uid` defaults to the main dashboard because that is where most tabs live. A tab
    module that builds onto the health dashboard (#431) must pass `uid=HEALTH_UID`
    for a link to one of its own tabs — otherwise the link targets a same-named tab
    on the OTHER dashboard, which is the class of navigation bug that looks like it
    worked. `tests/test_links.py` resolves every `dtab` against the destination
    dashboard's real layout, so getting this wrong fails the build.
    """
    return data_link(title, uid=uid, tab=(domain, leaf), loki=loki,
                     variables=variables)
