package zenarmor

// Fixtures. The conn/dns/tls/http documents below are REAL, copied verbatim out of a
// 2,824-document capture taken from a production Zenarmor on 2026-07-16. They are not
// hand-written, and they are the reason several fields here are named nothing like the
// spec guessed.
//
// alert and sip have NO real fixture: neither family produced a single document during
// the capture window, so the two below are minimal plausible constructions from
// Zenarmor's documented shape. Treat any assertion about their field NAMES as
// unverified until a real alert is captured; what they genuinely prove is the
// family-independent behaviour (subsystem, action, severity, body).

// A real conn document. start_time 1784224295000, end_time 1784224415000: a flow held
// open for two minutes, which is exactly the gap that makes start_time the wrong
// timestamp to ship.
const connDoc = `{"transport_proto":"UDP","policyid":"0","cloud_policyid":"2LD3owZ8cU","cloud_ruleid":"","cloud_networkid":"","interface":"ixl0","vlanid":"0","conn_uuid":"418a309b-1b40-42b0-b39e-03726055ff8c","direction":"out","src_hwaddr":"bc2411c1d512","src_username":"","ip_src_saddr":"10.0.0.114","ip_src_port":55309,"src_hostname":"10.0.0.114","src_dir":"EGRESS","dst_hwaddr":"98b78521aff2","dst_username":"","ip_dst_saddr":"10.0.0.254","ip_dst_port":1900,"dst_hostname":"10.0.0.254","dst_dir":"INGRESS","is_blocked":0,"is_overlay":0,"organization":"","overlay_transport_type":"none","is_local":1,"input":1,"output":1,"src_npackets":1,"src_nbytes":0,"src_pbytes":94,"dst_npackets":0,"dst_nbytes":0,"dst_pbytes":0,"src_tcp_flags":"","dst_tcp_flags":"","start_time":1784224295000,"end_time":1784224415000,"encryption":"Clear","app_id":34,"app_proto":"SSDP","app_name":"SSDP","app_category":"Network Management","tags":["Local Bound"],"security_tags":[],"web_actions":[],"web_actions_description":[],"src_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"dst_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"device":{"id":"bc2411c1d512","name":"opnsense-devel","category":"other","vendor":"","os":"","osver":""},"remote_device":"","community_id":"1:tecORBpGbqEAiZw4rUmpJB5C6yM=","handshake_result":"None"}`

// A real dns document. Note: NO end_time, and the category taxonomy arrives as
// domain_categories, an ARRAY.
const dnsDoc = `{"start_time":1784224414000,"transport_proto":"UDP","policyid":"0","cloud_policyid":"2LD3owZ8cU","cloud_ruleid":"","cloud_networkid":"","interface":"ixl0","vlanid":"50","conn_uuid":"1016dae1-b8ff-4dc7-9911-d80ed58228d6","direction":"out","src_hwaddr":"bc2411bca12e","src_username":"","ip_src_saddr":"10.0.50.152","ip_src_port":57464,"src_hostname":"10.0.50.152","src_dir":"EGRESS","dst_hwaddr":"01005e0000fc","dst_username":"","ip_dst_saddr":"224.0.0.252","ip_dst_port":5355,"dst_hostname":"224.0.0.252","dst_dir":"INGRESS","is_blocked":0,"is_overlay":0,"organization":"","overlay_transport_type":"none","is_local":1,"encryption":"Clear","src_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"dst_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"device":{"id":"bc2411bca12e","name":"WINSRV","category":"other","vendor":"","os":"","osver":""},"remote_device":"","community_id":"1:l+E8Koa8/kdQUD+vGbWw9BTJiAw=","security_tags":[],"trans_id":25244,"query":"WINSRV","qclass":"IN","qtype":"ALL","answers":"","ttls":"","total_answers":0,"is_AA":0,"is_TC":0,"is_RD":0,"is_RA":0,"is_request":1,"is_response":0,"resp_code":-1,"domain_categories":[]}`

// A real tls document. Note: NO end_time, and its category taxonomy is the singular
// string "category", not "domain_categories".
const tlsDoc = `{"start_time":1784224405000,"transport_proto":"TCP","policyid":"0","cloud_policyid":"2LD3owZ8cU","cloud_ruleid":"","cloud_networkid":"","interface":"ixl0","vlanid":"50","conn_uuid":"034126eb-4034-4379-a556-bd155f4dfb8a","direction":"out","src_hwaddr":"14133347fcfb","src_username":"","ip_src_saddr":"10.0.50.2","ip_src_port":35264,"src_hostname":"10.0.50.2","src_dir":"EGRESS","dst_hwaddr":"020000000032","dst_username":"","ip_dst_saddr":"61.145.136.88","ip_dst_port":6001,"dst_hostname":"www.tinionet.net","dst_dir":"INGRESS","is_blocked":0,"is_overlay":0,"organization":"","overlay_transport_type":"none","is_local":0,"encryption":"TLS-Encrypted","src_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"dst_geoip":{"timezone":"","continent_code":"","city_name":"Guangdong","country_name":"China","country_code2":"CN","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":23.13170051574707,"longitude":113.26599884033203,"location":{"lat":23.13170051574707,"lon":113.26599884033203}},"device":{"id":"14133347fcfb","name":"bobcatminer","category":"iot","vendor":"AzureWave Technology Inc.","os":"","osver":""},"remote_device":"","community_id":"1:cVYJGcKUJ4mGRmh39U0rvUK0H0I=","server_name":"www.tinionet.net","category":"Uncategorized","session_id":"","ja3":"d4532a81f32dbfb55a549c648cddc3da"}`

// A real http document. Note: NO end_time, and the response status is "status_msg".
const httpDoc = `{"start_time":1784224408000,"transport_proto":"TCP","policyid":"0","cloud_policyid":"2LD3owZ8cU","cloud_ruleid":"","cloud_networkid":"","interface":"ixl0","vlanid":"50","conn_uuid":"1884fbfe-3ac8-40ef-b361-d24a490aedb7","direction":"out","src_hwaddr":"1c0b8b3c19e6","src_username":"","ip_src_saddr":"10.0.50.228","ip_src_port":58580,"src_hostname":"10.0.50.228","src_dir":"EGRESS","dst_hwaddr":"020000000032","dst_username":"","ip_dst_saddr":"10.0.0.11","ip_dst_port":8080,"dst_hostname":"10.0.0.11","dst_dir":"INGRESS","is_blocked":0,"is_overlay":0,"organization":"","overlay_transport_type":"none","is_local":1,"encryption":"Clear","src_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"dst_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"device":{"id":"1c0b8b3c19e6","name":"UPSGarage","category":"network","vendor":"Ubiquiti Inc","os":"","osver":""},"remote_device":"","community_id":"1:CdzDWxUWwmQfUDE++ATaLE4WRew=","method":"POST","version":"HTTP/1.1","host":"10.0.0.11","category":"","user_agent":"ESP32 HTTP Client/1.0","web_action":"","web_action_description":"","referrer":"","uri":"/inform","status_msg":"200","cli_hdr_names":"Host,Content-Type,Content-Length","srv_hdr_names":"Content-Type,Content-Length,Date","cookie_vars":"","uri_vars":"","proxied":"","browser":"","rtap":{"status":"safe","report_url":"","screenshot_url":"","brand_name":""},"req_body_len":4488,"rsp_body_len":163}`

// Constructed, NOT captured: no alert fired during the capture window. Field names
// follow Zenarmor's documented alert shape.
const alertDoc = `{"start_time":1784224400000,"end_time":1784224401000,"transport_proto":"TCP","interface":"ixl0","ip_src_saddr":"10.0.50.2","ip_src_port":44322,"ip_dst_saddr":"93.184.216.34","ip_dst_port":443,"is_blocked":1,"alert_category":"Attempted Administrator Privilege Gain","alert_severity":"1","alertinfo":{"signature":"ET EXPLOIT Possible CVE-2021-44228","category":"Attempted Administrator Privilege Gain","sid":2034647,"severity":"1"},"device":{"id":"14133347fcfb","name":"bobcatminer"}}`

// Constructed, NOT captured: no SIP traffic crossed the box during the capture window.
const sipDoc = `{"start_time":1784224400000,"transport_proto":"UDP","interface":"ixl0","ip_src_saddr":"10.0.50.9","ip_src_port":5060,"ip_dst_saddr":"10.0.0.20","ip_dst_port":5060,"is_blocked":0,"sip_method":"INVITE","sip_uri":"sip:1001@pbx.local","sip_status":"200"}`

// A real dns document that was actually answered: resp_code 0 (NOERROR) and a populated
// domain_categories array. The dnsDoc above has resp_code -1 (the request, no response
// yet) and an empty array, so both shapes are covered.
const dnsAnsweredDoc = `{"start_time":1784224459000,"transport_proto":"UDP","policyid":"0","cloud_policyid":"2LD3owZ8cU","cloud_ruleid":"","cloud_networkid":"","interface":"ixl0","vlanid":"25","conn_uuid":"8bb36fb8-f00e-470f-a94b-fea57b420da9","direction":"out","src_hwaddr":"bc24112b5391","src_username":"","ip_src_saddr":"10.0.25.136","ip_src_port":60065,"src_hostname":"10.0.25.136","src_dir":"EGRESS","dst_hwaddr":"020000000019","dst_username":"","ip_dst_saddr":"10.0.25.254","ip_dst_port":53,"dst_hostname":"10.0.25.254","dst_dir":"INGRESS","is_blocked":0,"is_overlay":0,"organization":"","overlay_transport_type":"none","is_local":1,"encryption":"Clear","src_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"dst_geoip":{"timezone":"","continent_code":"","city_name":"","country_name":"","country_code2":"","country_code3":"","dma_code":"0","region_name":"","region_code":"","postal_code":"","area":"0","metro":"0","asn":"0","latitude":0.0,"longitude":0.0,"location":{"lat":0.0,"lon":0.0}},"device":{"id":"bc24112b5391","name":"WINSRV","category":"other","vendor":"","os":"","osver":""},"remote_device":"","community_id":"1:YZ41IikpcZwKBiEo53Vnkv9vQKI=","security_tags":[],"trans_id":42818,"query":"time.windows.com","qclass":"IN","qtype":"A","answers":"10.0.0.2","ttls":"479","total_answers":1,"is_AA":0,"is_TC":0,"is_RD":1,"is_RA":1,"is_request":1,"is_response":1,"resp_code":0,"domain_categories":["Technology and Computer"]}`
