apiVersion: v2
name: opnsense-exporter
description: Secure single-firewall Prometheus exporter deployment for OPNsense
type: application
version: 0.1.0
appVersion: main
keywords:
  - opnsense
  - prometheus
  - exporter
home: https://github.com/rknightion/opnsense-exporter
sources:
  - https://github.com/rknightion/opnsense-exporter
maintainers:
  - name: rknightion
