#!/usr/bin/env bash
# gen_oui.sh — regenerate internal/webui/oui_data.txt from the IEEE registry.
#
# Provenance: IEEE Standards OUI (MA-L) public registry.
#   Source CSV: https://standards-oui.ieee.org/oui/oui.csv
#   Columns:    Registry,Assignment,Organization Name,Organization Address
#
# The embedded table (internal/webui/oui_data.txt) is a *curated* subset: only
# the vendors in the VENDORS map below are kept, each mapped to a short,
# human-friendly display name. This keeps the embedded binary small while still
# resolving the manufacturers common on a home/SMB network. To resolve a vendor
# that is currently missing, add a pattern to the VENDORS list and re-run.
#
# To regenerate the FULL table (all ~40k registered OUIs) instead, drop the
# vendor filter: emit every row as "ASSIGNMENT\tOrganization Name". That bloats
# the binary by a few MB, which is why the shipped table is curated.
#
# Usage:
#   ./scripts/gen_oui.sh                 # download + regenerate oui_data.txt
#   OUI_CSV=/path/to/oui.csv ./scripts/gen_oui.sh   # use a local CSV copy
#
# Format of each output line: uppercase 6-hex prefix, a TAB, the short vendor
# name, e.g.  B827EB<TAB>Raspberry Pi
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$here/internal/webui/oui_data.txt"
csv="${OUI_CSV:-}"

tmp=""
if [[ -z "$csv" ]]; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  echo "downloading https://standards-oui.ieee.org/oui/oui.csv ..." >&2
  curl -sSL --max-time 120 https://standards-oui.ieee.org/oui/oui.csv -o "$tmp"
  csv="$tmp"
fi

OUI_CSV="$csv" OUT="$out" python3 - <<'PY'
import csv, os, re

# Ordered (regex, short-name) pairs; first match wins. Patterns match the IEEE
# "Organization Name" column case-insensitively.
VENDORS = [
    (r"\bapple\b", "Apple"),
    (r"raspberry pi", "Raspberry Pi"),
    (r"espressif", "Espressif"),
    (r"\bcisco\b", "Cisco"),
    (r"\bmeraki\b", "Cisco Meraki"),
    (r"\bintel\b", "Intel"),
    (r"tp-link|tplink", "TP-Link"),
    (r"ubiquiti", "Ubiquiti"),
    (r"netgear", "Netgear"),
    (r"samsung", "Samsung"),
    (r"vmware", "VMware"),
    (r"google", "Google"),
    (r"amazon", "Amazon"),
    (r"\bmicrosoft\b", "Microsoft"),
    (r"dell\b", "Dell"),
    (r"hewlett[ -]?packard|hp inc|hpe\b|aruba", "HP/Aruba"),
    (r"sonos", "Sonos"),
    (r"xiaomi", "Xiaomi"),
    (r"\blg electronics\b|\blg innotek\b", "LG"),
    (r"sony", "Sony"),
    (r"huawei", "Huawei"),
    (r"asustek|asus\b", "ASUS"),
    (r"d-link|dlink", "D-Link"),
    (r"juniper", "Juniper"),
    (r"nintendo", "Nintendo"),
    (r"roku", "Roku"),
    (r"synology", "Synology"),
    (r"qnap", "QNAP"),
    (r"avm gmbh|avm audiovis", "AVM (FRITZ!)"),
    (r"mikrotik|routerboard", "MikroTik"),
    (r"zyxel", "Zyxel"),
    (r"realtek", "Realtek"),
    (r"nest labs", "Google Nest"),
    (r"\bring llc\b|\bring\b.*amazon", "Ring"),
    (r"signify|philips lighting|koninklijke philips", "Philips/Signify"),
    (r"texas instruments", "Texas Instruments"),
    (r"nordic semiconductor", "Nordic Semi"),
    (r"tuya", "Tuya"),
    (r"sonoff|itead", "Sonoff/ITEAD"),
    (r"shelly|allterco", "Shelly"),
    (r"fortinet", "Fortinet"),
    (r"\bpalo alto\b", "Palo Alto"),
    (r"proxmox", "Proxmox"),
    (r"\bqemu\b|\bkvm\b", "QEMU/KVM"),
    (r"oracle.*virtual|virtualbox", "VirtualBox"),
    (r"\bhonor device\b", "Honor"),
    (r"oneplus", "OnePlus"),
    (r"oppo\b|guangdong oppo", "OPPO"),
    (r"vivo mobile", "vivo"),
    (r"motorola", "Motorola"),
    (r"lenovo", "Lenovo"),
    (r"\bacer\b", "Acer"),
    (r"\bmsi\b|micro-star", "MSI"),
    (r"gigabyte", "Gigabyte"),
    (r"\bamazon technologies\b", "Amazon"),
]
COMPILED = [(re.compile(p, re.I), name) for p, name in VENDORS]

seen = {}
with open(os.environ["OUI_CSV"], newline="", encoding="utf-8", errors="replace") as f:
    for row in csv.DictReader(f):
        assign = (row.get("Assignment") or "").strip().upper()
        org = (row.get("Organization Name") or "").strip()
        if len(assign) != 6 or not re.fullmatch(r"[0-9A-F]{6}", assign):
            continue
        for rx, name in COMPILED:
            if rx.search(org):
                seen[assign] = name
                break

lines = [f"{k}\t{v}" for k, v in sorted(seen.items())]
with open(os.environ["OUT"], "w", encoding="utf-8") as f:
    f.write("# Curated OUI (MAC prefix -> vendor) table for the web UI devices page.\n")
    f.write("# Generated by scripts/gen_oui.sh from the IEEE MA-L registry.\n")
    f.write("# Source: https://standards-oui.ieee.org/oui/oui.csv\n")
    f.write("# Format: <6-hex-uppercase-prefix>\\t<short vendor name>\n")
    f.write("\n".join(lines))
    f.write("\n")
print(f"wrote {len(lines)} OUI entries to {os.environ['OUT']}")
PY
