#!/usr/bin/env bash
# notices.sh — regenerate the third-party software notices for the SHIPPED binary.
#
# Emits THIRD_PARTY_NOTICES.md: for every Go module in the import graph of the
# opnsense2otel main package (repo root, "."), the module name + version +
# detected license + source URL, followed by the verbatim LICENSE text and (where
# present) the verbatim NOTICE file — the latter satisfying Apache-2.0 §4(d). Our
# own module is excluded.
#
# This is a RELEASE ARTIFACT, not a committed file: it changes on every dependency
# bump, so committing+gating it would break Renovate automerge (hosted Renovate
# can't self-regenerate it). Instead the image build bakes it into /licenses/ and
# the release pipeline attaches it to the GitHub Release. Output is deterministic
# (sorted, byte-stable) for a given module set, so independent regenerations agree.
#
# Env:
#   GO_LICENSES   go-licenses binary (default: go-licenses on PATH; just passes .tools/)
#   TARGET        package to analyse (default: . — the root main package)
#   OUT           output file (default: THIRD_PARTY_NOTICES.md)
set -euo pipefail

GO_LICENSES="${GO_LICENSES:-go-licenses}"
TARGET="${TARGET:-.}"
OUT="${OUT:-THIRD_PARTY_NOTICES.md}"
SELF="github.com/rknightion/opnsense2otel"
TMPL="$(cd "$(dirname "$0")" && pwd)/notices.tsv.tmpl"

# go-licenses resolves license files from the module cache, so force module mode
# (this repo commits vendor/ and builds with -mod=vendor; vendor mode would hide
# the cache paths go-licenses needs).
export GOFLAGS="${GOFLAGS:--mod=mod}"

command -v "$GO_LICENSES" >/dev/null 2>&1 || {
  echo "notices: go-licenses not found ('$GO_LICENSES') — run 'just notices'" >&2
  exit 1
}

# go-licenses reads LICENSE/NOTICE files from the module cache; make sure it's populated.
go mod download

# One go-licenses pass -> TSV (name<TAB>version<TAB>license<TAB>url<TAB>licensePath), sorted
# byte-stably by module name. stderr carries only benign "non-Go code"/"empty version" warnings;
# a hard failure still propagates via pipefail (the exit code survives 2>/dev/null).
tsv="$(mktemp)"
trap 'rm -f "$tsv"' EXIT
"$GO_LICENSES" report "$TARGET" --template "$TMPL" --ignore "$SELF" 2>/dev/null \
  | LC_ALL=C sort -t "$(printf '\t')" -k1,1 > "$tsv"

[ -s "$tsv" ] || { echo "notices: go-licenses produced no modules — aborting" >&2; exit 1; }

{
  cat <<'HDR'
# Third-Party Software Notices

<!-- GENERATED by `just notices` (go-licenses). DO NOT EDIT BY HAND. -->
<!-- This file is a build/release artifact regenerated on every dependency change; it is
     baked into the container image at /licenses/ and attached to each GitHub Release. -->

opnsense2otel is licensed under **Apache-2.0** (see LICENSE / LICENSING.md). The
compiled binary incorporates the third-party Go modules listed below. Each module's license
text — and its NOTICE file where one is provided (Apache-2.0 §4(d)) — is reproduced verbatim.
These modules retain their own upstream licenses; the combined binary is distributed under
Apache-2.0.

## Bundled data: DB-IP Lite (#549)

This section is written by hand rather than derived from go-licenses, because go-licenses
reports only Go MODULES and the databases below are data the container image carries, not
code the binary links. Do not delete it as "not generated" — it is a licence condition.

The container image bundles the DB-IP Lite IP-to-Country and IP-to-ASN databases at
`/usr/share/opnsense2otel/geoip/`, fetched unmodified at image build time from
https://db-ip.com and redistributed byte-for-byte (never adapted, merged or trimmed).

**IP geolocation data by DB-IP (https://db-ip.com), licensed under CC BY 4.0
(https://creativecommons.org/licenses/by/4.0/).**

The same credit ships in the image at `/licenses/GEOIP-DB-IP-ATTRIBUTION.txt`, on the
documentation site (docs/geoip.md) and in the operator console footer. Binary-only
distributions (the release archives) carry no database and no obligation, but the credit is
stated here regardless — it costs nothing and a notices file that varies by artifact is a
notices file someone eventually ships without it.
HDR

  while IFS="$(printf '\t')" read -r name version lic url path; do
    [ -n "$name" ] || continue
    printf '\n================================================================================\n'
    printf '%s (%s)\n' "$name" "$version"
    printf 'License: %s\n' "$lic"
    printf 'Source: %s\n' "$url"
    printf -- '--------------------------------------------------------------------------------\n'
    if [ -n "$path" ] && [ -f "$path" ]; then
      cat "$path"
    else
      printf '(no license file detected by go-licenses)\n'
    fi
    # Apache-2.0 §4(d): include the sibling NOTICE file if the module ships one.
    if [ -n "$path" ]; then
      dir="$(dirname "$path")"
      for n in NOTICE NOTICE.txt NOTICE.md notice notice.txt; do
        if [ -f "$dir/$n" ]; then
          printf '\n----- NOTICE (%s) -----\n' "$name"
          cat "$dir/$n"
          break
        fi
      done
    fi
  done < "$tsv"
} > "$OUT.tmp"
mv -f "$OUT.tmp" "$OUT"

echo "notices: wrote $OUT ($(grep -c '^License: ' "$OUT") modules)"
