"""Gate: no panel queries an `opnsense_*` metric the exporter cannot emit (#591).

## Why this file exists

The coverage gate has always run in one direction — catalogue to panel — and it is
loud about the answer ("1020/1020 catalogue metrics referenced"). Nobody checked the
other direction, and PromQL cannot check it for anyone: an unknown metric name is not
a syntax error, it is an empty vector, so `tools/promqlcheck` passes it and Grafana
renders "No data" with no indication that the name was never real.

The cost was measured rather than hypothesised. The Overview's headline **CPU Busy %**
tile queried `100 - opnsense_activity_cpu_idle_percent` from the first dashboard commit
to #591. That metric has never existed in any release — zero hits in the Go source,
absent from both generated catalogue documents — so `100 - <empty vector>` was an empty
vector and the most prominent tile on the dashboard read "No data" for its entire life
while every gate in the repo stayed green.

## What it does not cover

Non-`opnsense_`-prefixed runtime metrics (`up`, `go_*`, `process_*`) are structurally
invisible to the catalogue, whose row regex admits only `opnsense_`-prefixed names.
They are covered by `RUNTIME_METRIC_LEDGER` and `tests/test_runtime_ledger.py`, not
here — widening this gate's regex would only produce a gap for every runtime metric,
since none of them can ever be in the catalogue.
"""
import sys
import unittest
from pathlib import Path

GRAFANA_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(GRAFANA_DIR))

import build_dashboard  # noqa: E402
from builder import Builder  # noqa: E402


def probe(expr: str) -> dict:
    """Run the gate over ONE planted expression on an otherwise empty Builder.

    A fresh Builder rather than a real one on purpose: these cases assert what the
    tokenizer does with a specific shape, and running them against the live estate
    would make them fail for whatever unrelated gap the estate happens to carry —
    which is precisely how a behaviour test degrades into a second copy of the gate.
    """
    b = Builder()
    b.record_expr(expr)
    return build_dashboard.panel_metric_gaps(b)


def family():
    """Every Builder in the dashboard family (#431). Family-wide for the same reason
    `coverage()` is: a panel is a panel wherever it is rendered."""
    return [b for _, b in build_dashboard.build_family()]


class PanelMetricGapTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.builders = family()

    def test_no_panel_queries_a_metric_outside_the_catalogue(self):
        gaps = build_dashboard.panel_metric_gaps(*self.builders)
        self.assertEqual(
            {}, gaps,
            "panel(s) query an opnsense_* metric that is in neither generated "
            "catalogue, so they can only ever render No data. Fix the name, or — if "
            "the reference is deliberate — add it to PANEL_METRIC_EXEMPT in "
            "build_dashboard.py with a written reason:\n  "
            + "\n  ".join(f"{token}  <-  {expr}" for token, expr in sorted(gaps.items())))

    def test_the_scan_sees_a_realistic_number_of_expressions(self):
        """Guards the guard. A structural change to `_exprs` would otherwise make the
        assertion above vacuously pass on an empty scan, which is exactly how a gate
        stops working without anyone noticing."""
        exprs = [e for b in self.builders for e in b._exprs]
        self.assertGreater(len(exprs), 900)

    def test_a_planted_nonexistent_metric_is_caught(self):
        """The gate has teeth. Without this, a scan that silently matched nothing
        would pass `test_no_panel_queries_a_metric_outside_the_catalogue` forever.

        Uses the real defect #591 found, so this doubles as the regression pin for the
        CPU Busy % tile: if anyone reintroduces `opnsense_activity_cpu_idle_percent`,
        the gate that would have caught it is proven to still work."""
        gaps = probe('sum by (opnsense_instance) (opnsense_activity_cpu_idle_percent{})')
        self.assertIn("opnsense_activity_cpu_idle_percent", gaps)

    def test_recording_rule_outputs_are_not_reported_as_gaps(self):
        """`instance:opnsense_pf_state:utilization` is a recording-rule OUTPUT name,
        generated by grafana/alerts/build_rules.py and correctly absent from the
        exporter's catalogue. A tokenizer that ignored the colons would pull
        `opnsense_pf_state` out of the middle of it and report ~13 false gaps."""
        gaps = probe('instance:opnsense_pf_state:utilization{opnsense_instance=~"$opnsense_instance"}')
        self.assertEqual({}, gaps)

    def test_a_metric_whose_own_name_ends_in_count_is_not_mangled(self):
        """`_bucket`/`_sum`/`_count` are stripped only as a FALLBACK. Stripping first
        would turn `opnsense_firmware_upgrade_packages_count` — a real catalogue
        metric — into a nonexistent base name and report it as a gap."""
        catalogue = set(build_dashboard.load_catalogue())
        self.assertIn("opnsense_firmware_upgrade_packages_count", catalogue,
                      "fixture metric renamed; pick another catalogue metric ending "
                      "in _count/_sum/_bucket")
        gaps = probe('opnsense_firmware_upgrade_packages_count{}')
        self.assertEqual({}, gaps)

    def test_the_exempt_list_carries_a_reason_for_every_entry(self):
        """Same contract as COVERAGE_EXEMPT: an entry without a reason is an
        allowlist that nobody can review."""
        for token, reason in build_dashboard.PANEL_METRIC_EXEMPT.items():
            self.assertTrue(reason and reason.strip(),
                            f"PANEL_METRIC_EXEMPT[{token!r}] has no written reason")


if __name__ == "__main__":
    unittest.main()
