"""Cross-surface guard for #418 and #464, widened by #591.

Prometheus/OTLP convention is that a monotonic sum (a Prometheus COUNTER) exports
with a `_total` suffix. The exporter's supported live backend is OTLP-fed, and
OTLP -> Prometheus canonicalization appends `_total` to every counter regardless
of what name the Go code declared it with. A Counter-typed metric declared
WITHOUT `_total` therefore produces two different names depending on backend
(direct /metrics vs the OTLP-bridged Prometheus that real deployments query),
and any dashboard panel or alert rule written against the unsuffixed name
returns no data on the supported live backend once that series exists.

This derives each metric's Prometheus export name and instrument type from the
generated catalogues and asserts every `opnsense_*` metric name referenced anywhere
in the generated dashboards or the generated Grafana-managed alert/recording rules
that the catalogue types as Counter ends in `_total`.

#418 fixed the eight firewall pf pass/block descriptors; #464 fixed the
remaining nine (ipsec phase1/phase2 byte+packet counters, vnstat bytes_total).
The guard is unconditional — there is no known-violations exemption to update
when adding a new counter; get the name right the first time.

## What #591 widened, and why it was LATENT rather than live

The guard read types from `docs/metrics/metrics.md` alone and scanned
`grafana/dashboard.json` alone. Both halves of that were blind in the same place, so
they compounded: `metrics.md` is generated by walking the COLLECTOR registry, which
cannot see any metric registered elsewhere — the whole `opnsense_exporter_logs_*`
family, the annotations writer, the OTLP delivery series — and `dashboard.json` is
only one of the two dashboards this project generates, with **79 metrics living
exclusively on the health dashboard** since the #431/#523 split. A Counter declared
without `_total` in `internal/logship` and charted on the health dashboard was
invisible to this file twice over.

There were ZERO violations at the time of widening, so this is hardening, not a
bug fix, and it is expected to stay green. That matters for how a future failure
should be read: this file going red means a genuinely new violation, not a backlog
finally becoming visible.

## The naming trap — do NOT "fix" it

`opnsense_exporter_series_total` is a **Gauge** whose name ends in `_total`. It
counts the series on the collector registry right now; it can and does go down.
The convention this file enforces runs one way only — a Counter must end `_total` —
and says nothing about what may end `_total`, so the gauge is correct as named and
correctly ignored here. Renaming it would break every dashboard and alert that reads
it to satisfy a rule that does not exist. `test_the_series_total_gauge_is_not_a_false_positive`
pins that reading so nobody has to rediscover it.
"""
import glob
import re
import unittest
from pathlib import Path

GRAFANA_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = GRAFANA_DIR.parent
METRICS_MD = REPO_ROOT / "docs" / "metrics" / "metrics.md"
# The exporter's own self-metrics, source-scanned rather than registry-walked (#428).
# Found the same way `build_dashboard.load_catalogue()` finds it, and for the same
# reason: neither document alone sees everything the exporter emits.
SELF_METRICS_MD = REPO_ROOT / "docs" / "metrics" / "self-metrics.md"
DASHBOARD_JSON = GRAFANA_DIR / "dashboard.json"
# The self-observability companion (#431). 79 metrics are charted here and nowhere
# else, so scanning only the file above checked barely half the estate.
DASHBOARD_HEALTH_JSON = GRAFANA_DIR / "dashboard-health.json"
GRAFANA_MANAGED_DIR = GRAFANA_DIR / "alerts" / "grafana-managed"

CATALOGUE_ROW_RE = re.compile(r"\|\s*(opnsense_[a-z0-9_]+)\s*\|\s*(\w+)\s*\|")
METRIC_NAME_RE = re.compile(r"opnsense_[a-z0-9_]+")

# The source-scanned inventory reports the DECLARATION kind, and honestly reports
# `Desc` for a `prometheus.NewDesc` because a Desc carries no instrument type at all —
# the type is chosen later, at MustNewConstMetric time. `metrics.md` is generated from
# that emission (see scripts/docgen/type_resolution_test.go), so where the two
# disagree it is the one holding evidence and it wins. `test_the_two_catalogues_only_
# disagree_in_the_expected_direction` asserts every disagreement really is of that
# shape, so a future Counter-vs-Gauge conflict fails loudly instead of being silently
# resolved by precedence.
UNTYPED_DECLARATION = "Desc"


def _load_rows(path) -> dict:
    types = {}
    with open(path) as f:
        for line in f:
            m = CATALOGUE_ROW_RE.match(line)
            if m:
                types[m.group(1)] = m.group(2)
    return types


def load_catalogue_types() -> dict:
    """metric name -> documented Type ("Counter"/"Gauge"/...), from BOTH generated
    catalogues. Mirrors build_dashboard.load_catalogue()'s row-matching regex and its
    two-source union; see the module docstring for the precedence rule."""
    types = dict(_load_rows(SELF_METRICS_MD))
    types.update(_load_rows(METRICS_MD))
    return types


def referenced_metric_names(*paths) -> set:
    names = set()
    for path in paths:
        with open(path) as f:
            names |= set(METRIC_NAME_RE.findall(f.read()))
    return names


class CounterMetricsEndInTotalTest(unittest.TestCase):
    """#418: a Counter-typed metric consumed by either generated dashboard or the
    generated Grafana-managed alert/recording rules must end in `_total`, or it
    silently returns no data against the supported OTLP-fed live backend."""

    def test_dashboard_and_managed_alerts_counters_end_in_total(self):
        catalogue = load_catalogue_types()
        self.assertTrue(catalogue, "expected a non-empty metrics catalogue")

        managed_files = sorted(glob.glob(str(GRAFANA_MANAGED_DIR / "*.json")))
        self.assertTrue(managed_files, "expected grafana-managed alert manifests")

        referenced = referenced_metric_names(
            DASHBOARD_JSON, DASHBOARD_HEALTH_JSON, *managed_files)

        violations = []
        for name in sorted(referenced):
            if catalogue.get(name) == "Counter" and not name.endswith("_total"):
                violations.append(name)

        self.assertEqual(
            [], violations,
            "Counter-typed metrics referenced in the generated dashboards/alerts "
            "must end in _total (OTLP->Prometheus canonicalization appends it "
            "regardless of the Go-declared name, so the unsuffixed name returns "
            f"no data on the supported live backend): {violations}",
        )

    def test_the_self_metric_inventory_reaches_the_type_table(self):
        """Guards the widening itself. If SELF_METRICS_MD stopped being parsed, the
        assertion above would go on passing while silently checking half the estate
        again — which is the state #591 found it in."""
        catalogue = load_catalogue_types()
        for metric in (
            "opnsense_exporter_logs_shipped_total",        # internal/logship
            "opnsense_exporter_annotations_written_total",  # internal/annotations
            "opnsense_exporter_otlp_exports_total",         # internal/telemetry
        ):
            self.assertEqual(
                "Counter", catalogue.get(metric),
                f"{metric} is typed Counter in docs/metrics/self-metrics.md but did "
                "not reach this file's type table; the union with metrics.md is broken")

    def test_the_health_dashboard_is_actually_scanned(self):
        """The other half of the widening. The health dashboard owns metrics that
        appear nowhere in dashboard.json, so a scan that quietly dropped it would be
        undetectable from the pass/fail result alone."""
        main_only = referenced_metric_names(DASHBOARD_JSON)
        both = referenced_metric_names(DASHBOARD_JSON, DASHBOARD_HEALTH_JSON)
        self.assertGreater(
            len(both - main_only), 20,
            "the health dashboard contributes almost no metrics the main dashboard "
            "lacks; either it was not read or the two files have converged, and "
            "either way this guard's second surface needs re-checking")

    def test_the_two_catalogues_only_disagree_in_the_expected_direction(self):
        """Both documents type the ten `internal/collector` meta metrics they share.
        Every disagreement today is `metrics.md` naming a real instrument type where
        the source scan could only see an untyped `prometheus.NewDesc`, which is why
        metrics.md takes precedence. A disagreement of any OTHER shape means one of
        the generators is wrong, and precedence would hide it."""
        collector_types = _load_rows(METRICS_MD)
        self_types = _load_rows(SELF_METRICS_MD)
        unexpected = {
            name: (collector_types[name], self_types[name])
            for name in collector_types.keys() & self_types.keys()
            if collector_types[name] != self_types[name]
            and self_types[name] != UNTYPED_DECLARATION
        }
        self.assertEqual(
            {}, unexpected,
            "the two generated catalogues type the same metric differently, and not "
            "in the benign untyped-Desc direction. Precedence would silently pick "
            f"metrics.md; resolve it in docgen instead: {unexpected}")

    def test_the_series_total_gauge_is_not_a_false_positive(self):
        """`opnsense_exporter_series_total` is a Gauge ending in `_total` and must
        stay that way. Pinned so a future reader does not "fix" the name to satisfy a
        symmetry this rule does not have — the convention is Counter => `_total`, not
        `_total` => Counter."""
        catalogue = load_catalogue_types()
        self.assertEqual("Gauge", catalogue.get("opnsense_exporter_series_total"),
                         "opnsense_exporter_series_total is a Gauge; it reports the "
                         "current series count on the collector registry and goes "
                         "down as well as up")
        referenced = referenced_metric_names(DASHBOARD_JSON, DASHBOARD_HEALTH_JSON)
        self.assertIn("opnsense_exporter_series_total", referenced,
                      "the trap metric is no longer charted, so this pin no longer "
                      "guards anything; delete it or repoint it")


if __name__ == "__main__":
    unittest.main()
